@startuml
left to right direction
skinparam shadowing false

interface Struct

interface Tuple {
  + left: Term
  + right: Term
  + {static} of(left: Term, right: Term): Tuple
  + {static} of(**varargs** items: Term): Tuple
  + {static} of(items: Iterable<Term>): Tuple
}

Struct <|-- Tuple
@enduml