/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchiddiagrams: String = "io.github.javaeden.orchid:OrchidDiagrams:" +
            Versions.io_github_javaeden_orchid

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchiddocs: String = "io.github.javaeden.orchid:OrchidDocs:" +
            Versions.io_github_javaeden_orchid

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidkotlindoc: String = "io.github.javaeden.orchid:OrchidKotlindoc:" +
            Versions.io_github_javaeden_orchid

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidplugindocs: String = "io.github.javaeden.orchid:OrchidPluginDocs:" +
            Versions.io_github_javaeden_orchid

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
        "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
                Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_common: String = "org.jetbrains.kotlin:kotlin-stdlib-common:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_js: String = "org.jetbrains.kotlin:kotlin-stdlib-js:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test_annotations_common: String =
        "org.jetbrains.kotlin:kotlin-test-annotations-common:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test_common: String = "org.jetbrains.kotlin:kotlin-test-common:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test_js: String = "org.jetbrains.kotlin:kotlin-test-js:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test_junit: String = "org.jetbrains.kotlin:kotlin-test-junit:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://github.com/gciatto/kt-math
     */
    const val kt_math_js: String = "io.github.gciatto:kt-math-js:" + Versions.io_github_gciatto

    /**
     * https://github.com/gciatto/kt-math
     */
    const val kt_math_jvm: String = "io.github.gciatto:kt-math-jvm:" + Versions.io_github_gciatto

    /**
     * https://github.com/gciatto/kt-math
     */
    const val kt_math_metadata: String = "io.github.gciatto:kt-math-metadata:" +
            Versions.io_github_gciatto

    /**
     * http://www.antlr.org
     */
    const val antlr4: String = "org.antlr:antlr4:" + Versions.org_antlr

    /**
     * http://www.antlr.org
     */
    const val antlr4_runtime: String = "org.antlr:antlr4-runtime:" + Versions.org_antlr

    const val org_danilopianini_git_sensitive_semantic_versioning_gradle_plugin: String =
        "org.danilopianini.git-sensitive-semantic-versioning:org.danilopianini.git-sensitive-semantic-versioning.gradle.plugin:" +
                Versions.org_danilopianini_git_sensitive_semantic_versioning_gradle_plugin

    const val org_jetbrains_kotlin_multiplatform_gradle_plugin: String =
        "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin:" +
                Versions.org_jetbrains_kotlin_multiplatform_gradle_plugin

    const val de_fayard_buildsrcversions_gradle_plugin: String =
        "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
                Versions.de_fayard_buildsrcversions_gradle_plugin

    const val com_eden_orchidplugin_gradle_plugin: String =
        "com.eden.orchidPlugin:com.eden.orchidPlugin.gradle.plugin:" +
                Versions.com_eden_orchidplugin_gradle_plugin

    const val org_jetbrains_dokka_gradle_plugin: String =
        "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:" +
                Versions.org_jetbrains_dokka_gradle_plugin

    const val com_jfrog_bintray_gradle_plugin: String =
        "com.jfrog.bintray:com.jfrog.bintray.gradle.plugin:" +
                Versions.com_jfrog_bintray_gradle_plugin
}
