import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val com_fasterxml_jackson_dataformat: String = "2.11.2"

    const val io_github_javaeden_orchid: String = "0.21.1"

    const val org_jetbrains_kotlin: String = "1.4.10"

    const val org_antlr: String = "4.8-1"

    const val org_danilopianini_git_sensitive_semantic_versioning_gradle_plugin: String = "0.2.2"

    const val com_github_breadmoirai_github_release_gradle_plugin: String = "2.2.12"

    const val org_jetbrains_kotlin_multiplatform_gradle_plugin: String = "1.4.10"

    const val com_github_johnrengelman_shadow_gradle_plugin: String = "6.0.0"

    const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String = "9.4.0"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val com_eden_orchidplugin_gradle_plugin: String = "0.21.1"

    const val org_jetbrains_dokka_gradle_plugin: String = "0.10.1" // available: "1.4.10"

    const val com_jfrog_bintray_gradle_plugin: String = "1.8.5"

    const val jackson_datatype_jsr310: String = "2.11.2"

    const val clikt_multiplatform: String = "2.8.0"

    const val jackson_core: String = "2.11.2"

    const val plantuml: String = "1.2020.2" // available: "8059"

    const val kt_math: String = "0.2.2"

    const val ktlint: String = "0.39.0"

    /**
     * Current version: "6.6.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.6.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
