name: deploy-js
on:
  workflow_run:
    workflows:
      - check
    types:
      - completed
    branches:
      - master
env:
  PROJECT_NAME: 2p-kt
  WORKFLOW: deploy-js
jobs:
  deploy-on-npm:
    runs-on: ubuntu-latest
    name: Deploy on NPM
    if: github.event.workflow_run.conclusion == 'success'
    # && github.event.ref_type == 'tag'
    timeout-minutes: 60
    concurrency:
      # Only one release job at a time. Strictly sequential.
      group: release-npm
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.5

      - name: Compile and Release NPM modules
        uses: DanySK/build-check-deploy-gradle-action@2.1.21
        with:
          build-command: ./gradlew compileKotlinJs
          check-command: true
          deploy-command: ./gradlew npmPublish
          should-deploy: true
          npm-token: ${{ secrets.NPM_TOKEN }}
